### ISSUE TITLE
후원사 신청 용어 통일

### ISSUE THREAD

**Issue by emscb** [pythonkr/pyconkr-web#104]
![image](https://user-images.githubusercontent.com/32407677/57589516-6f3b2200-755f-11e9-97aa-1f11f2dda61d.png)

"스폰서 모집"이라는 말(2군데)이 전부 위에 뜨는 메뉴와 같게 "후원사 신청"으로 바뀌어야 할 듯합니다.
저 2군데가 어떤 파일에 적혀있는지를 못찾았어요

**Comment by amazingguni** [comment]
여깁니다!

https://github.com/pythonkr/pyconkr-web/blob/634a3703bfa2d2a286a6d61d7f45ddfefee222e5/locales/ko-KR.json#L30

**Comment by amazingguni** [comment]
수정완료!
