### ISSUE TITLE
개인후원자 리스트 페이지

### ISSUE THREAD

**Issue by iiogmgo** [pythonkr/pyconkr-web#116]

**Comment by aveclumiere** [comment]
![image](https://user-images.githubusercontent.com/14121134/58603174-bac52e00-82ca-11e9-8673-05a587f4132d.png)

안녕하세요.
개인 후원자 리스트 페이지의 기본 화면에 오탈자가 있어서 업로드합니다.
혹시나 이미 수정하신 내용이라면 죄송합니다.

**Comment by Mabin-J** [comment]
수정되어있군요.
https://github.com/pythonkr/pyconkr-web/blob/develop/static/locales/ko/sponsor.json#L91

**Comment by amazingguni** [comment]
수정 완료! 감사합니다♥
