### ISSUE TITLE
기존에 제출한 제안서 확인 불가

### ISSUE THREAD

**Issue by NovemberOscar** [pythonkr/pyconkr-web#128]
`/contribute/proposing-a-talk` 페이지에서 보이는 화면이 현재 이렇게 제출한 제안서를 확인 또는 수정할 수 있다고 안내하고 있습니다
![image](https://user-images.githubusercontent.com/20695897/58389840-d92bef00-8068-11e9-8e82-2b0017f334e1.png)
하지만 버튼을 눌러 링크를 따라가 보면 제안서를 수정 또는 확인할 수 있는 화면이 존재하지 않습니다.

**Comment by amazingguni** [comment]
@NovemberOscar 
수정 완료하였습니다 :) 다시 확인해보시겠어요?

**Comment by NovemberOscar** [comment]
잘 동작합니다! 💪
