### ISSUE TITLE
과거 파이콘 한국 페이지에 접속하면 redirection이 반복적으로 발생합니다.

### ISSUE THREAD

**Issue by lqez** [pythonkr/pyconkr-web#152]
문제점:
https://pycon.kr/2015/ 또는 https://www.pycon.kr/2015/ 등의 예전 주소로 접속하려고 하면 계속해서 페이지 리다이렉션이 발생합니다. 어떤 주소로 접속하면 좋을까요?

<img width="641" alt="Screen Shot 2019-06-10 at 7 57 25 PM" src="https://user-images.githubusercontent.com/579366/59191261-fceb4b00-8bb9-11e9-89a3-96a94f28ee39.png">

제안:
과거 사이트들의 도메인이 변경되었다해도, 링크 보존을 위해 적절한 페이지 이동을 제공해주면 좋을 것 같습니다. 과거 사이트의 도메인 또는 새로운 위치를 알려주시면 기여할 수 있도록 해보겠습니다.

**Comment by amazingguni** [comment]
@lqez
과거 파이콘 홈페이지들을 archive.pycon.kr로 이전하였습니다.
사이트 개선 작업 중에 redirect가 유실되어 생긴 문제로 지금은 수정된 상태입니다 :)
https://archive.pycon.kr 이나 https://www.pycon.kr/2018 로 접속 부탁드립니다.

**Comment by lqez** [comment]
확인 감사합니다. :D
