### ISSUE TITLE
스프린트 제안을 위한 버튼이 표시되지 않습니다.

### ISSUE THREAD

**Issue by lqez** [pythonkr/pyconkr-web#153]
https://www.pycon.kr/contribute/overview 페이지에 표시된 스프린트 신청 기간임에도, 신청할 수 있는 버튼이 표시되지 않고 있습니다. (로그인된 상태입니다)
<img width="726" alt="Screen Shot 2019-06-11 at 3 35 08 PM" src="https://user-images.githubusercontent.com/579366/59248874-953b0b80-8c5e-11e9-8d58-4fc02282c88a.png">

**Comment by amazingguni** [comment]
@lqez 
스프린트 제안 일정이 확정되지 않은 상태에서 날짜가 노출되었던 것 같습니다.
일정이 정해지는데로 SNS, 홈페이지 등으로 공지를 하도록 하겠습니다.
현재는 날짜를 삭제한 상태입니다.

**Comment by lqez** [comment]
확인 감사합니다! [스프린트서울](https://sprintseoul.org)이라는 작은 스프린트 모임을 진행하고 있는데, 8월 모임은 생략하고 파이콘 한국 스프린트에 참가하려고 하던 차에 발견했었습니다. :) 갱신되면 신청하도록 하겠습니다.
