### ISSUE TITLE
ticket 페이지에서 '컨퍼런스 얼리버드'가 아직도 '구매'로 나옵니다.

### ISSUE THREAD

**Issue by Mabin-J** [pythonkr/pyconkr-web#163]
https://www.pycon.kr/ticket/overview 페이지에서 
컨퍼런스 얼리버드가 아직도 `구매`로 표기되고 있습니다.

더 이상 구매할 수 없는 티켓이니, 수정하거나 빼야할 것 같습니다.

**Comment by dev-nicelee** [comment]
@Mabin-J 해당 이슈 처리되었습니다. 감사합니다🙇🏻‍♂️
