### ISSUE TITLE
후원사 신청 페이지 이동 불가

### ISSUE THREAD

**Issue by emscb** [pythonkr/pyconkr-web#170]
![image](https://user-images.githubusercontent.com/32407677/59581290-5ea63a80-910f-11e9-89bf-ba8537113c9a.png)

이후 "정말로 다 읽었습니다"를 눌러도 다음 페이지로 넘어가지 않습니다.

![image](https://user-images.githubusercontent.com/32407677/59581306-6bc32980-910f-11e9-96fa-73c71c8a4a8d.png)

체크가 다시 다 풀립니다. 데브 서버도 마찬가지 입니다.

**Comment by dev-nicelee** [comment]
@emscb 이슈 감사합니다. d041f9088cc84060359bd6732e5346f8dba899aa 에서 처리되었습니다.
