### ISSUE TITLE
CFP 편집 페이지에서 여러개의 동일한 인풋박스

### ISSUE THREAD

**Issue by NovemberOscar** [pythonkr/pyconkr-web#192]
https://www.pycon.kr/account/editproposal/cfp
페이지에서 Topic, Contents of CFP detail이 중복되어 여러개 나타나고 있습니다.
![image](https://user-images.githubusercontent.com/20695897/60267646-ad30b180-9925-11e9-9054-c65b1d976cf5.png)
![image](https://user-images.githubusercontent.com/20695897/60267666-b883dd00-9925-11e9-80d3-d6fafb22d46f.png)

**Comment by amazingguni** [comment]
@NovemberOscar 
두 개 인풋박스 각각 한글/영문을 받기 위해 넣어두었는데,
영문화에서 라벨이 동일하게 적혀 있는 문제가 있었습니다.
현재는 수정된 상태입니다 😄 제보 감사드립니다!
