### ISSUE TITLE
스프린트 상세 페이지가 배경만 뜬 채 내용이 나오지 않습니다.

### ISSUE THREAD

**Issue by dahlia** [pythonkr/pyconkr-web#220]
이슈를 이 저장소에 만들어야 할 지, API 쪽 저장소에 만들어야 할 지 모르겠어서, 일단 이곳에 남깁니다. [스프린트 목록](https://www.pycon.kr/program/sprint)에서 특정 프로젝트 링크를 눌러서 들어가면 (예: <https://www.pycon.kr/program/sprint-detail?id=180>), 분홍색 배경은 뜨는데 내용이 뜨지 않습니다. 아래는 스크린샷입니다.

![](https://user-images.githubusercontent.com/12431/60771156-80974980-a11e-11e9-8086-dc097e40d414.png)

개발자 도구를 띄워서 확인해 보니 `https://www.pycon.kr/api/graphql`로 `POST` 요청을 보내는데 `400 Bad Request` 오류가 나고 있습니다. 이 때문인지 모르겠는데, 아무튼 응답 내용이 이렇습니다.

```json
{
  "errors": [
    {
      "type": "GraphQLError",
      "message": "Cannot query field \"numOfParticipants\" on type \"SprintNode\".",
      "code": "error"
    }
  ]
}
```

참고로 macOS + Mozilla Firefox를 이용했습니다 (`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0`).

**Comment by amazingguni** [comment]
쿼리가 변경된 것이 반영되지 않았던 것 같습니다. 현재는 수정되었습니다 :smile: 
제보 감사드립니다 :cry: 
https://github.com/pythonkr/pyconkr-web/pull/221/commits/b41c71d075e1aa15203950924ccc17b12ded36f5
