### ISSUE TITLE
게임 후원페이지 이미지 깨짐

### ISSUE THREAD

**Issue by M1zz** [pythonkr/pyconkr-web#230]
아무 이미지도 입력하지 않았을 때 이미지 깨짐
기본이미지가 필요해보임

**Comment by amazingguni** [comment]
흐에엥 ㅠ-ㅠ

**Comment by cmygray** [comment]
페이스북으로 가입하신 분들의 프로필 이미지를 못찾아서 그런 것 같습니다.
![image](https://user-images.githubusercontent.com/26966551/61168855-291a3300-a58f-11e9-8559-62449022a1ba.png)
