### ISSUE TITLE
모바일 화면에서 프로필 사진 크기 깨짐

### ISSUE THREAD

**Issue by MilenaLee** [pythonkr/pyconkr-web#244]
![image](https://user-images.githubusercontent.com/19401376/61222081-ed30ca80-a754-11e9-8c55-ae13989459a3.png)

위 사진과 같이 컨퍼런스, 튜토리얼, 스프린트 디테일 페이지에서 프로필 사진 크기가 깨집니다

**Comment by amazingguni** [comment]
수정 완료되었습니다 :smile:
제보 감사드립니다!
