### ISSUE TITLE
영문화 진행이 덜 된 페이지 목록

### ISSUE THREAD

**Issue by iiogmgo** [pythonkr/pyconkr-web#29]
로그인 여부 X
- [x] https://www.pycon.kr/account/privacy-policy?lang=en-US
- [x] https://www.pycon.kr/contribute/recommending-a-keynote-speaker
- [x] https://www.pycon.kr/contribute/cfp-detailed-guide
- [x] https://www.pycon.kr/contribute/proposing-a-talk
- [x] https://www.pycon.kr/sponsor/prospectus

로그인 후
- [x] https://www.pycon.kr/account/contribution
- [x] https://www.pycon.kr/account/agreement?lang=en-US

**Comment by chukycheese** [comment]
음 저는 저 페이지들 다 영문으로 보이는 것 같아요. 

다만 며칠 남았는지 알려주는 부분 등의 배너는 아직 한글이네요 ㅠㅠ 

https://www.pycon.kr/account/contribution 이 부분도 영문화가 필요하네요.

**Comment by iiogmgo** [comment]
@chukycheese 부분이라도 안 된 페이지들이라 리스팅 되었어요
