### ISSUE TITLE
스폰서 제안 제출 레이아웃 줄 안맞음

### ISSUE THREAD

**Issue by emscb** [pythonkr/pyconkr-web#55]
![image](https://user-images.githubusercontent.com/32407677/56016960-cd929c00-5d38-11e9-8e73-8a8f4d402925.png)

줄이 안맞는 문제가 있습니다.
이전 / 임시 저장 / 다음
모두가 줄이 제각각입니다.

**Comment by XoDNr** [comment]
@emscb 님 요고 브라우저 종류와 버전까지 알 수 있을까요 !!

**Comment by emscb** [comment]
@XoDNr 
![image](https://user-images.githubusercontent.com/32407677/56086891-0ba7d100-5e9b-11e9-94cb-12acbed5a51f.png)

크롬 버전입니다! (버전 73.0.3683.103(공식 빌드) (64비트))

**Comment by dev-nicelee** [comment]
@emscb PR https://github.com/pythonkr/pyconkr-web/pull/64 에서 스타일 조정 후 반영 완료.

감사합니다🙇🏻‍♂️
