### ISSUE TITLE
후원사 정보 작성 페이지에서 ai 파일이 업로드되지 않습니다.

### ISSUE THREAD

**Issue by yeoneui-hong** [pythonkr/pyconkr-web#60]
1.5MB 크기의 로고 ai 파일을 업로드했는데 올라가지 않습니다. 
ai 파일 업로드를 눌러도 현재 파일명이 뜨는 위치에 아무것도 보여지지 않아서,
혹시나싶어 png 파일을 넣었는데 이 파일은 잘 올라갑니다.

브라우저는 크롬, 버전은 73.0.3683.86이고 mac os입니다.

![image](https://user-images.githubusercontent.com/46517999/56125697-7862be80-5fb4-11e9-9269-ec17a2c0315c.png)

**Comment by amazingguni** [comment]
그..그러네요 시무룩

**Comment by amazingguni** [comment]
`413 Request Entity Too Large` 네요 nginx 설정을 수정하도록 하겠습니다

**Comment by amazingguni** [comment]
@yeoneui-hong 

200M로 늘렸습니다 😄 

```
client_max_body_size 100M;
```
