### ISSUE TITLE
스폰서 정보 작성 완료 시 버튼 이름 변경 제안

### ISSUE THREAD

**Issue by yeoneui-hong** [pythonkr/pyconkr-web#61]
현재는 스폰서 정보를 작성하고 '다음' 버튼을 누르면 제출 완료 화면이 뜨는데요.
'다음'을 누르면 뭔가 더 있을 줄 알았는데 바로 제출 완료가 되어서 조금 놀랐어요.
버튼 이름을 '제출'로 바꿔보면 어떨지 제안드려봅니다 :)

**Comment by dev-nicelee** [comment]
@yeoneui-hong 폼 제출 마지막단계일 경우 필요한 경우인 것 같아서 적용 예정입니다. [PR 참조](https://github.com/pythonkr/pyconkr-web/pull/81) 부탁드릴게요.

**Comment by dev-nicelee** [comment]
@yeoneui-hong Develop 브랜치에 반영완료되어 이슈를 닫습니다. 테스트 후 문제 없을 경우 Master에도 반영하도록 하겠습니다.
