### ISSUE TITLE
영문 버전에서 제안 및 신청 보기 문구가 잘못되있음

### ISSUE THREAD

**Issue by amazingguni** [pythonkr/pyconkr-web#66]
![Screenshot_20190418-105539_Chrome](https://user-images.githubusercontent.com/13607839/56332094-f2b85c00-61c9-11e9-846d-afc8b590c3ff.jpg)

**Comment by cmygray** [comment]
https://github.com/alibaba/react-intl-universal#message-with-variables

locale 문구에 variable을 삽입할 때 이름이 일치해야 하네요.
일단 en-US.json 파일을 수정해서 해결할 수 있지만, intl.get 메소드 파라미터 커스텀 타입을 추가해서 존재하지 않는 이름의 variable 전달 시 타입에러가 나도록 할 수 있을 것 같아요.
