### ISSUE TITLE
locale 파일에 정의된 variable, 전달되는 실제 값의 key를 대조하는 도구 필요

### ISSUE THREAD

**Issue by cmygray** [pythonkr/pyconkr-web#75]

**Comment by dev-nicelee** [comment]
아래 사항들을 확인해보았으나 결국 공식 [Github 이슈](https://github.com/yahoo/react-intl/issues/1265)로 요청한 상태입니다.

- Editor extension (VSCode, Atom ..)
- React Intl API
- Json Utils

더 좋은 방법이 있다면 코멘트 부탁드리겠습니다. 😎

**Comment by dev-nicelee** [comment]
@cmygray 장기 이슈로 닫도록 하겠습니다. 현재까지는 해결방법을 찾지 못했습니다..
