### ISSUE TITLE
Conference 티켓 구매 상태 페이지 및 등록/참석 확인증 페이지 구현

### ISSUE THREAD

**Issue by amazingguni** [pythonkr/pyconkr-web#82]
<img width="887" alt="스크린샷 2019-04-25 오후 4 41 46" src="https://user-images.githubusercontent.com/13607839/56718875-97aed800-677a-11e9-9aaf-9352f4e41472.png">
<img width="808" alt="스크린샷 2019-04-25 오후 4 42 09" src="https://user-images.githubusercontent.com/13607839/56718876-97aed800-677a-11e9-85be-91058a24fede.png">
<img width="1242" alt="스크린샷 2019-04-25 오후 4 45 29" src="https://user-images.githubusercontent.com/13607839/56718877-97aed800-677a-11e9-8248-ee2fe6563b90.png">

**Comment by iiogmgo** [comment]
완 뇨
