### ISSUE TITLE
마감일자 D-Day 잘못 표기됨

### ISSUE THREAD

**Issue by Nerd-Bear** [pythonkr/pyconkr-web#86]
마감 D-Day가 D--73으로 잘못 표기됨

https://www.pycon.kr/account/contribution
![image](https://user-images.githubusercontent.com/26026903/56864295-c4bded80-69fb-11e9-8529-cd10d021d52b.png)

**Comment by amazingguni** [comment]
수정되었습니다! 감사합니다 😄
