### ISSUE TITLE
오픈 리뷰 페이지 D-Day 표기 오류

### ISSUE THREAD

**Issue by emscb** [pythonkr/pyconkr-web#89]
![1](https://user-images.githubusercontent.com/32407677/57411528-d176e880-7228-11e9-9222-f2eb7122614f.png)

D-10이 아닌 D10으로 표기됨

**Comment by XoDNr** [comment]
영문 버전에서는 잘 뜨나 한글 버전만 그렇네유..

**Comment by amazingguni** [comment]
#86 과 동일한 이유로 발생하는 이슈입니다 :cry
