### ISSUE TITLE
오픈 리뷰 CFP 내용에 불필요한 내용

### ISSUE THREAD

**Issue by emscb** [pythonkr/pyconkr-web#90]
![2](https://user-images.githubusercontent.com/32407677/57411567-efdce400-7228-11e9-9426-71a9fa6ccb15.png)

1, 2와 같이 `/LONG`이 붙는 경우와
4와 같이 `/SHORT`가 붙는 경우가 있습니다.
모든 발표 제안에 대해 난이도, 배경지식 뒤에 붙어있어요.

**Comment by amazingguni** [comment]
요게 사실 발표 시간을 의미하는데.. 더 자세한 설명으로 교체해야겠군요

**Comment by emscb** [comment]
@amazingguni 아 그거였군요, 그냥 빼도 괜찮을 것 같아요

**Comment by amazingguni** [comment]
그럼 25분 40분으로 좀 더 이해하기 쉽도록 변경시킬게요 :) @emscb

**Comment by amazingguni** [comment]
수정되었습니다 😄
