### ISSUE TITLE
발표 제안 검토하기 페이지에서 페이스북 로그인을 누를 경우 오류 발생

### ISSUE THREAD

**Issue by yeoneui-hong** [pythonkr/pyconkr-web#95]
1. 로그인하지 않은 상태에서 
2. https://dev.pycon.kr/contribute/proposal-review 링크로 접속
3. 로그인 버튼 클릭
![image](https://user-images.githubusercontent.com/46517999/57499565-18dda180-731b-11e9-815e-fdd4d8f86a74.png)
4. 깃헙 로그인은 문제 없는데 페이스북 로그인을 누를 경우
5. 아래 오류가 발생
![image](https://user-images.githubusercontent.com/46517999/57499580-2f83f880-731b-11e9-9cbe-90e4db49910f.png)
6. 확인 버튼을 누르면 다음처럼 뜹니다. 다시 확인 눌러도 계속 반복해서 뜹니다.
![image](https://user-images.githubusercontent.com/46517999/57499596-3a3e8d80-731b-11e9-8230-4d0b604644ef.png)
7. 로그인을 못했습니다..

**Comment by dev-nicelee** [comment]
@yeoneui-hong 브라우저 환경은 어떻게 되시나요?

**Comment by yeoneui-hong** [comment]
Chrome입니당
버전 74.0.3729.131(공식 빌드) (64비트)

**Comment by dev-nicelee** [comment]
@amazingguni https://dev.pycon.kr/account/login?redirect_url=/contribute/proposal-review 리다이렉트 url whitelist 등록을 해야하는 건가요?

**Comment by amazingguni** [comment]
네 ㅠ_ㅠ 또 깜박을..

**Comment by amazingguni** [comment]
@yeoneui-hong 수정햇습니다!

**Comment by yeoneui-hong** [comment]
잘됩니다 여러분!!!!
